### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by Micah1101** [iiDk-the-actual/iis.Stupid.Menu#67]
Hi, I've been using your menus since update 3.6.1 and for some reason, the newest update is having issues.

My virus detector is detecting the dll as a Trojan:Win32/Wactac.B!ml

If this is just because of the new update then i have no idea why it says this

**Comment by iiDk-the-actual** [comment]
This is because of Windows Defender, and it's partially my fault. Due to the web requests and files written and downloaded, it gets falsely flagged as malware. This self corrects itself over time, as the more people that download the menu, the less it'll get false detected. There's nothing I can really do about this, sadly.

**Comment by connordasdsadsadsa** [comment]
bet thanks i went in a lobby an someone said it was a rat

**Comment by beastmoderinworld** [comment]
I wish you wrote the software in a way that did not flag as a virus, because I have to trust what my av tells me

**Comment by noahpittwood** [comment]
I have reasonable suspicion that this may be malware
on virus total if you out it through, 4 anti viruses will detect that instantly and warn you, 
if it was 1 I would suspect it is a false pos but 4? that sounds like a virus or something is poorly designed
